on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup frontend
      run: |
        cd frontend/
        npm i
    - name: Terraform init
      run: |
        terraform init
    - name: Terraform apply
      run: |
        terraform apply -auto-approve
    - name: Store Terraform state
      run: |
        git checkout -b tfstate
        git add ./terraform.tfstate -f
        git config user.name "TFState"
        git commit -m "Updating TFState"
        git push -u origin tfstate
